### ISSUE TITLE
HazardFlow pipelined cpu structure with regard to lab2(branch predictor)

### ISSUE THREAD

**Issue by JongyCysec** [kaist-cp/cs492-uarch#25]
I've tried to sketch the structure of first three cpu pipeline (fetch, decode, exe) implemented by hazardflow design with regard to lab2 (branch predictor).

I'm not sure whether all the specific comments and types are valid or not. 
It will be meaningful if some other students get help from the structure and 
it will be very helpful if someone else points out some errors or modify/complement the structure.

![image](https://github.com/user-attachments/assets/f68160b8-5a27-469f-9726-7299a99132c2)

Leave the URL for modification/complemenation.

https://app.diagrams.net/#G1-Ozeu2-2i138ylAvP2cd_VND89gwboCG#%7B%22pageId%22%3A%22C0vsTpqooSxowkVAgLYY%22%7D

**Comment by minseongg** [comment]
First of all, you did a great job! Thank you for your hard work.

One point I would like to mention is that the branch predictor update signal is not shown in the diagram. Since the `fsm_map` updates its state based on the ingress payload and the current state, the branch predictor update signal should be passed to the ingress payload of the **M4**. To do this, the payload signals between **M1** and **M4** should contain `HOption<BpUpdate>` in their type (e.g., `(u32, HOption<BpUpdate>)` instead of `u32`).

We have improved the description related to this in [Section 2.4](https://docs.google.com/document/d/1Wro8OlRvQIpgcMETTiafJG97XvP78DSQs-QcwlqZ-to/edit#heading=h.sn5q6txxy07). Please check the updated description for more details!

**Comment by JongyCysec** [comment]
@minseongg 

# Question 1. About Branch Predictor Update Signal

I've misunderstood the route of branch predictor update signal.

(1) At first, I've thought that M4 would deal with ```BpUpdate``` in resolver type ```DecR```. So, I did not specify the flow of ```BpUpdate``` from M1 to M4. 

(2) However, what you intended is that such ```BpUpdate``` in resolver is routed to M0 (fetch), sourced as payload, and finally delivered to M4 to be handled. 

So, I wonder what is difference between (1) & (2). 
It is clear that ```BpUpdate``` will be handled earlier in (1) than (2). I wonder whether both (1) & (2) both ensure correctness. 

# Question 2. About each ```reg_fwd``` module in each stage.
I wonder what is the main purpose or functionality of ```reg_fwd``` module.
(It is said that it delays one or more cycles by storing ingress payload into its state.)

**Comment by minseongg** [comment]
### Answer to Question 1:

Let me explain the motivation behind the design where the branch predictor is updated from the ingress payload.

In general, the stateful combinators (e.g., `fsm_map`, `fsm_ingress`, `fsm_egress`) defined in the HazardFlow standard combinator library are designed to update their internal state when an **ingress transfer** or **egress transfer** occurs. This approach was used to understand the circuit at a higher level from the perspective of a dataflow graph.

And this is why, in the assignment description, the branch predictor in M4 is updated from the ingress payload rather than directly from the egress resolver (even though the latter could update the branch predictor in an earlier cycle). By packing the redirection PC with its corresponding branch predictor update signals as M4's ingress payload, we can ensure that the state update occurs in the same cycle as the ingress transfer. So you can understand the intention behind this design is to provide a higher-level understanding of the circuit from a dataflow graph perspective.

Of course, as you mentioned in Scenario 2, you can also use a generic FSM combinator (`fsm`) to update the branch predictor directly from the egress resolver. You can use the design provided in the assignment description as a reference!

### Answer to Question 2:

The `reg_fwd` in each stage is used to represent the "pipeline register" between stages. It stores the next PC (in the fetch stage) or result of the previous stage (in other stages) and allows the circuit to execute multiple instructions in a pipelined manner, where each stage processes a different instruction simultaneously.

As you mentioned, removing `reg_fwd` may reduce the number of cycles required for each instruction, but it would increase the amount of computation per cycle, leading to a higher clock frequency and lower CPU performance. For more details on pipelining, please refer to the following: [Wikipedia](https://en.wikipedia.org/wiki/Instruction_pipelining#Concept_and_motivation), [TechTarget](https://www.techtarget.com/whatis/definition/pipelining#:~:text=The%20biggest%20advantage%20of%20pipelining,the%20delay%20between%20completed%20instructions.)

**Comment by JongyCysec** [comment]
I got what you mean. 
So, main functionality / works of module would be done on ingress/egress payload transfer while resolver transfer is subsidiary. 

Thank you for your sincere explanation.
