### ISSUE TITLE
[Lab3] Kill Resolver of Muldiv

### ISSUE THREAD

**Issue by JongyCysec** [kaist-cp/cs492-uarch#44]
I'm not sure about what ```kill``` resolver of ```muldiv``` module.

I've suspected that ```kill``` signal implies ```redirect``` signal of ```MemR``` which is set due to csr exception because the terminology("kill") was used as pipeline flush at fetch/decode stage of Lab2.

So, I tried to send additional ```kill``` signal to ```muldiv``` module based on ```redirect``` of ```MemR```.

However, I've founded that ```redirect``` of ```MemR``` is also considered at ```gen_payload``` function of ```exe``` stage.
(Specifically, ```gen_payload``` returns None for ```redirect``` signal)
Furthermore, if such ```kill``` signal implies ```redirect```, then it should be considered at ```base_alu``` module, too.

Therefore, I concluded that there is some problem with my understanding.
Can I get some help with such issues?

**Comment by minseongg** [comment]
First of all, as you mentioned, the `kill` signal to the `muldiv` module indicates that redirection has occurred in the memory stage. I will explain why the `kill` signal needs to be sent to the `muldiv` module, even though the later `filter_map` module discards the payload in the `gen_payload` function.

The `muldiv` module performs multiplication or division on the given `in1` and `in2` over multi-cycle, which is implemented as a finite state machine (FSM). You can check the states of the FSM [here](https://github.com/kaist-cp/hazardflow/blob/main/hazardflow-designs/src/cpu/multiplier.rs#L51-L75).

For example, performing a `Mul` operation is done with the following steps:

- The initial state of the multiplier is `Ready`. When it receives a request (`op`, `in1`, `in2`) from the ingress interface, the state is updated to `Mul` ([code](https://github.com/kaist-cp/hazardflow/blob/main/hazardflow-designs/src/cpu/multiplier.rs#L117-L142)).
- When the state is updated to `Mul`, the multiplication is performed over 32 cycles, and the state is kept as `Mul`. After the multiplication completes, the state is updated to `DoneMul` ([code](https://github.com/kaist-cp/hazardflow/blob/main/hazardflow-designs/src/cpu/multiplier.rs#L152-L184)).
- When the state is updated to `DoneMul`, the multiplier waits until the egress interface transfer occurs (i.e., until the egress ready signal becomes true). After the egress transfer happens, the state is updated to `Ready`, and waits for the next request ([code](https://github.com/kaist-cp/hazardflow/blob/main/hazardflow-designs/src/cpu/multiplier.rs#L215-L221)).

Now, let's assume that a redirection happens during the multiplication operation. In this case, the current operation must be flushed, and the multiplier state should be updated to `Ready` so that it can receive the next requests.

Therefore, the purpose of sending the kill signal to the `muldiv` module is to notify it to update its internal state to `Ready`.

On the other hand, the Base ALU completes all operations within a single cycle, so there is no state. Therefore, the `kill` signal does not need to be considered in the Base ALU.

I hope this answers your question. Feel free to ask further questions!

**Comment by JongyCysec** [comment]
@minseongg 
oh, i got what you mean. 
The main difference of logic of dealing with redirect comes from the cycle times that module takes and its internal state.

Thank you for your sincere answer. Sorry for my impatience that i would have understood the intention if i have gone through muldiv function carefully.
