### ISSUE TITLE
About parallelism between csr instruction and memory instruction

### ISSUE THREAD

**Issue by JongyCysec** [kaist-cp/cs492-uarch#45]
According to the implementation of RISC-V pipelined CPU via hazardflow, ```csr``` instructions are processed in Memory stage.

In case of ```Exe``` stage, ```base_alu``` instruction and ```muldiv``` instruction are branched.
And we limit the maximum number of concurrent instructions in the ```Exe``` stage to one by using ```exclusive``` wrapper.

However, such ```exclusive``` limitation is not applied to ```csr``` instruction and ```mem``` instruction in Memory stage.
So, I wonder whether there exists some problem with concurrent processing of ```csr``` & ```mem``` instructions or not.

### Q1. 
For example,  if ```csr``` instruction is on-processing in memory stage, subsequent ```mem``` instruction comes in parallel, and ```mem``` instruction is finished first, ( **I'm not sure this scenario can actually happen because normally ```mem``` instruction is expected to be much slower even if cached** )

then the effect of ```csr``` instruction will not be reflected to subsequent ```mem``` instruction even though```csr``` instruction might have changed some status (like privilege mode or memory access permissions).

### Q2. 
And I wonder the intention of locating ```csr``` processing logic into Memory stage.

**Comment by minseongg** [comment]
### Answer to Question 1:

In our baseline CPU, the maximum number of concurrent instructions in the memory stage is guaranteed to be 1 for the following reasons:

- Both `imem` and `dmem` are implemented as asynchronous memory, which provides a response in the same cycle as the request comes (apologies for not specifying this in the assignment description, even though it's quite an unrealistic design).
- CSR also provides a response in the same cycle as the request comes.
- There are no stalls in the writeback stage.

Therefore, there was no need to use `exclusive` in the baseline CPU's memory stage.

As you pointed out, in a more realistic scenario (e.g. when memory access takes more than one cycle), we would need to use `exclusive` to ensure that instructions are processed in an in-order manner. I will clarify this point in the assignment description. Sorry for the confusion, and thanks for always giving great questions.

### Answer to Question 2:

The CSR is in the memory stage in our baseline CPU because it was located in the memory stage in our reference design, the [riscv-sodor](https://github.com/ucb-bar/riscv-sodor) processor. Actually, the CSR's location can be arbitrarily decided (e.g., it can also be located in the decode stage).
