### ISSUE TITLE
```Reg_fwd``` behavior and debugging with GTKwave

### ISSUE THREAD

**Issue by JongyCysec** [kaist-cp/cs492-uarch#48]
## Description of GTKwave settings

- I run gtkwave on ```rv32um-p-mul.vcd```.
- As you can see from left window of the Picture1 below, five wires are  ```pc``` values in **ingress payload** of  ```reg_fwd``` module  of each stages. (I 've added wire descriptions in red color )

## Case 1 - Start of the program
**[Picture 1]**

![image](https://github.com/user-attachments/assets/fd3f447a-4ade-427f-98da-b7ac8f453dcf)
As you can check from Picture1, each instruction is pipelined in ```reg_fwd``` in each stage. 
For example, at time 1988ns, ```80000068```, ```80000064```, ```80000060```, ```8000005c```, ```80000058``` are stored in ```reg_fwd``` modules of ```Fetch```, ```Decode```, ```Exe```, ```Mem```, ```Wb``` stages. 
And it seems quite desirable and understandable. 

## Case 2 - Branch Prediction Fail & Flush(redirect)
**[Picture 2]**
![image](https://github.com/user-attachments/assets/401949e6-fb57-4472-bf2a-b486c0b1bec7)

**[Picture 3:  rv32um-p-mul.dump]**
![image](https://github.com/user-attachments/assets/f7bdca40-68e4-4ec6-8720-1b688a8c5550)

It seems that prediction of branch instruction (```0x80000148```) fails. (It should have jumped to ```0x80000160```).
Therefore, at 2108ns,
-  ```reg_fwd``` of ```Fetch``` is filled with proper instruction address (```0x80000160```) 
-  ```reg_fwd``` modules of ```Decode``` & ```Exe``` are flushed. 
- But ```reg_fwd``` of ```Mem``` & ```Wb``` stages are not flushed since instructions (```0x80000148```, ```0x80000144```) processed within ```Mem``` & ```Wb``` does not hurt valid program order. 

Thus, it seems quite desirable and understandable. 

## Case 3 - Processing Muldiv Instruction
**[Picture 4]**
![image](https://github.com/user-attachments/assets/e80e3641-fa6d-440c-a23c-2936f6e5b128)

**[Picture 5: rv32um-p-mul.dump]**
![image](https://github.com/user-attachments/assets/ccf3e927-35ac-4470-9633-cb0dbd3dd946)
At time 2150ns, ```mul```instruction(```0x800001a8```) is processed within ```Exe``` stage. 

- Since it takes 32 cycles to compute, ```0x800001a8``` value is not passed to ```reg_fwd``` of ```Mem``` at 2152ns. 
(You can check Picture 4)

- Since alu_ext is wrapped by ```exclusive``` and computation(```mul```) is on-processing, ```0x800001ac``` value from ```Decode``` is not passed to ```reg_fwd``` of ```Exe``` at 2152ns. 

- Since ```0x800001ac``` value is not transferred as egress payload at ```reg_fwd``` of ```Decode```, it cannot receive ingress payload ```0x800001b0``` value from ```Fetch```. 

Therefore, it seems quite desirable and understandable. 

## Questions ( + ```pipeline``` option of ```reg_fwd```)
I have two questions with regard to ```reg_fwd``` behavior.

(1) It will be really thankful if you check whether ```mul.vcd``` result and its analysis is valid or not.  
(2) Acutally, the ```pipeline``` options of each ```reg_fwd``` of each stages are turned on.
However, according to Picture 1&2, one cycle is delayed by ```reg_fwd``` even if ```pipeline``` option is turned on.

I've expected that pc value of each stage(```reg_fwd```) sholud have been able to be forwarded to next stages as much as possible if block does not happen in the path and ```pipeline``` option of ```reg_fwd``` is turned on.

But it was not. In fact, each instruction should have stayed at each stage at least one cycle as above pictures.

**Modified 10/25 : I 've been struggling with pipelining of ```reg_fwd``` issue. So I realize that ingress payload of ```reg_fwd``` should stay as a state at least one cycle in the module even if ```pipeline option``` is on. In specific, in case of ```reg_fwd```, value of ingress payload cannot be transferred as egress payload in the same cycle like other modules such as ```map```. ( In case of ```map```, the module leverages ingress payload for calculating egress payload. So it may not be proper to compare ```reg_fwd``` with ```map``` inherently). Is it right?**

**Comment by minseongg** [comment]
> It will be really thankful if you check whether `mul.vcd` result and its analysis is valid or not.

Yes, the waveform in `mul.vcd` and your analysis looks correct.

> Actually, the `pipeline` options of each `reg_fwd` of each stages are turned on.
However, according to Picture 1&2, one cycle is delayed by `reg_fwd` even if `pipeline` option is turned on.

It is intended that each payload should stay as a state at least one cycle even with `pipe` option is true.

Let me explain the behavior of `reg_fwd` combinator with the `pipe` option in more details.

**When `pipe` option is not enabled:**

In this case, the `reg_fwd` combinator turns on the ready signal only when the "internal state is empty" ([code](https://github.com/kaist-cp/hazardflow/blob/main/hazardflow-designs/src/std/combinators/reg.rs#L213)).

Here is the example waveform:



<p align="center">
  <img src="https://github.com/user-attachments/assets/aa3359f9-5dfe-47e5-b346-c295708ef3c5" height=40% />
</p>

- Cycle 0: Ingress transfer happens with payload `P1`.
- Cycle 1: State is now full with `P1` and egress transfer happens, **ingress transfer does not happen because state is full.**
- Cycle 2: Ingress transfer happens with payload `P2`.
- ...

You can see that the egress and ingress transfers cannot happen in the same cycle because egress valid signal turns on when the **state is full**, but ingress ready signal turns on when the **state is empty**.

In the CPU case study, if the `pipe` option is not enabled in `reg_fwd`, a stage cannot simultaneously send an instruction to the next stage and receive an instruction from the previous stage. It lowers the utilization and results in lower throughput.

To resolve this, we can enable the `pipe` option.

**When `pipe` option is enabled:**

In this case, the `reg_fwd` turns on the ready signal when either the "internal state is empty" or "internal state is full, but egress transfer happens so it will be empty at the next cycle" ([code](https://github.com/kaist-cp/hazardflow/blob/main/hazardflow-designs/src/std/combinators/reg.rs#L211)).

Here is the example waveform:



<p align="center">
  <img src="https://github.com/user-attachments/assets/7f3c69df-6535-4577-8b0e-d788e248b813" height=40% />
</p>

- Cycle 0: Ingress transfer happens with payload `P1`.
- Cycle 1: State is now full with `P1` and egress transfer happens. **Also, ingress transfer happens with payload `P2`.**
- Cycle 2: State is now full with `P2` and egress transfer happens. **Also, ingress transfer happens with payload `P3`**.
- ...

With `pipe` option enabled, the egress and ingress transfers can be happen in the same cycle, so it can achieve better throughput. Also in the CPU case study, now a stage can simultaneously send an instruction to the next stage and receive an instruction from the previous stage.

+) FYI: The term `pipe` comes from the [Chisel's Queue API](https://javadoc.io/static/edu.berkeley.cs/chisel3_2.12/3.2.1/chisel3/util/Queue.html#%3Cinit%3E(gen:T,entries:Int,pipe:Boolean,flow:Boolean)(implicitcompileOptions:chisel3.CompileOptions):chisel3.util.Queue[T]), which offers two options: `pipe` and `flow`. It seems the `flow` option is close to what you said, allows incoming data to pass through directly to the output without being held in the internal state. In our CPU, we do not use the `flow` option as it may create a long critical path, potentially reducing the frequency.

**Comment by JongyCysec** [comment]
Always thank you for your sincere answer. It is really helpful for me to understand the logic of ```reg_fwd```.
