### ISSUE TITLE
Data Hazard between Mem Stage and Exe Stage

### ISSUE THREAD

**Issue by JongyCysec** [kaist-cp/cs492-uarch#49]
When I analyzed the code (I'm worried that it may be wrong),

Data hazard is dealt in ```decode``` stage through ```ready``` function of ```DecH``` and ```gen_payload``` function.
(1) ```ready``` function of ```DecH``` stalls for load-use / CSR. 
(2) ```gen_payload``` function of ```decode``` stage determines the value of source registers by leveraging ```bypass``` value from ```Exe```, ```Mem```, and ```Wb```. 

Then, let's assume we run below code.
```
sub a4, a5, a6
lw a1, 4(a0)
add a3, a1, a2
```

When ```add``` instruction is processed in ```decode``` stage, ```lw``` & ```sub``` instruction would be processed in ```exe``` & ```mem``` stage.
Then, ```add``` does not suffer from stall but unfortunately it does not get up-to-date ```a1``` register value in my expectation.
That is because ```lw``` instruction is processed in ```exe``` stage and it does not send bypass value of ```a1``` yet. It will send up-to-date ```a1``` data from memory as ```bypass_from_mem``` at next cycle in ```mem``` stage.
 
So, I think that not only ```decode``` stage but also ```exe``` stage should be able to reflect ```bypass_from_mem``` value into its computation.
Can I ask you to verify whether there is something that I miss or mis-understand?
And can I ask you how such data hazard can be solved?

+ Of course, it is responsible for me to inspect whether there exists any provided test case which contains such instruction sequence. And I should have tested the case if any. I'm sorry. If you want to accuse me of laziness, I have nothing to say.

**Comment by minseongg** [comment]
Actually, the code you provided causes a load-use stall, similar to [this example](https://kaist-cp.github.io/hazardflow/book/examples/cpu/hazard.html#from-the-load-instruction) in the user guide.

In this case, the `add` instruction stalls in the decode stage to obtain the up-to-date value of `a1`.

Here is how it works at the code level:

**1. When the `lw` instruction is in the execute stage:**

- In the execute stage, the `stall` field of `ExeR` is set to `Some(a1)` by the `gen_resolver` logic ([code](https://github.com/kaist-cp/hazardflow/blob/main/hazardflow-designs/src/cpu/exe.rs#L107-L109)).
- In the decode stage, the `add` instruction causes `DecH::ready` to return false, as `exer.stall` is `Some(a1)` and `rs1_addr` is `a1` ([code](https://github.com/kaist-cp/hazardflow/blob/main/hazardflow-designs/src/cpu/decode.rs#L57-L65), there is no redirection). Therefore, the `add` instruction stalls in the decode stage.

**2. When the `lw` instruction is in the memory stage:**

- In the memory stage, as you mentioned, the up-to-date value of `a1` is computed and then set in the `bypass_from_mem` field of `MemR`.
- In the decode stage, the `add` instruction now receives the up-to-date value of `a1` and proceeds to the execute stage.

So, checking the `bypass_from_mem` value in the execute stage is unnecessary because the decode stage stalls until it read the up-to-date value of its source registers (by the [stall](https://github.com/kaist-cp/hazardflow/blob/main/hazardflow-designs/src/cpu/decode.rs#L61-L62) variable in the `DecH::ready`).

Could you please check this answers your question?

+) Do not hesitate to ask questions; it helps us identify confusing parts and improve the documentation! We encourage students to leave a question whenever something is unclear.

**Comment by JongyCysec** [comment]
@minseongg 
Oh, I missed the part where ```exer.stall``` is set for memory instruction. So, by using ```exer.stall```, the code implements unavoidable stall of load-use hazard. 

Thank you for your quick and easy to understand answer.

**Comment by JongyCysec** [comment]
@minseongg 
Can I ask one more question in addition to the previous one?

When ```decode``` stage fetches value of register for its source registers, it refers to ```bypass_from_*``` data and ```Regfile```.
The ```Regfile``` is passed from ```Wb``` stage as ```WbR```.
And ```Mem``` & ```Exe``` stage attaches its bypass value in ```MemR``` and ```ExeR```.

Then, is there any specific reason that the code attaches additional ```bypass_from_``` values into its ```Resolver``` instead of updating ```Regfile``` passed from ```Wb``` stage?
