### ISSUE TITLE
About Weight-Stationary & Output-Stationary of PE

### ISSUE THREAD

**Issue by JongyCysec** [kaist-cp/cs492-uarch#60]
# My understanding
I've understood that ```WS``` dataflow assumes that weight is stored in register(non-propagated register) of PE and uses it as weight while calculating mac result and ```OS``` dataflow assumes that partial sum is already stored in register of PE and uses it as ```acc``` while calculating mac result.

And preloading value (weight for ```WS``` and acc for ```OS```, ```in_top_data.d```) will be stored in propagate register.

# Provided 2*2 matrix multiplication  scenario

The specific procedures of 2 * 2 matrix multiplication with 2 * 2 tile is provided in the documentation and google slide.
(https://docs.google.com/presentation/d/1ff3mA6_p1RbSdiqRT4AH8pPiqOO6C6vVNCpPvkjrU9I/edit#slide=id.g3039a791452_1_1489)
![image](https://github.com/user-attachments/assets/48b2e4fb-aca6-43b4-91c2-cce3ca0e060a)

Then, I suspect that there is no ```WS``` dataflow in provided 2*2 matrix multiplication scenario. 
The reason why I suspect above is ...

- Weights input (B11, B12, B21, B22) plays as a weight twice in mac calculation. For example, in case of B11, it is used for calculating C11 and C21. (C11 = A11 * B11 + A12 * B21, C21 = A21 * B11 + A22 * B21).
- All weights (B11, B12, B21, B22) traverse two ```pe```s during the whole matrix multiplication.

The number of usages of weights and the number of ```pe``` that they go through are equivalent. 
I think we don't need ```WS``` dataflow for such scenario because weights don't have to be reused and I think there is no ```WS``` dataflow in goggle slide scenario. So it would be very thankful if you check it is right or wrong. 

# Mismatched matrix multiplication scenario.
Based on the understanding above, I think we can leverage ```WS``` dataflow if the dimension of multiplication is bigger than size of ```pe``` tile. 
In specific, we may assume calculating 8*8 matrix multiplication with 4 * 4 ```pe``` tile. 
So, I wonder how specific dataflow input can be written for calculating bigger matrix with smaller tile.

**Comment by minseongg** [comment]
You're right, the current scenarios in the Google Slides illustrate how the systolic array works with the `WS` dataflow configuration, but they does not reuse the weight matrix across multiple matmul operations (e.g., C=AxB followed by E=DxB, where B is the weight matrix).

As you mentioned, the most common case of reusing the weight matrix occurs when the matrices have size larger than the systolic array. In this case, the matmul operation is divided into multiple smaller matmul operations by the external controller.

We will add a more realistic example to the Google Slides that demonstrates how each dataflow configuration reuses values. Once it's done, I will notify you. Thank you for the question!

**Comment by woojinnn** [comment]
* General answer:
When calculating the matrix multiplication where the size of matrices are larger than the size of tile, splitting the matrix so that it can fit with the tile is required. Such functionality should be provided by the compiler or other components of hardware. If not, the developer should manually tile the matrix. (If you have had a chance for CUDA programming, probably you had a chance to do it as an exercise like [this](https://penny-xu.github.io/blog/tiled-matrix-multiplication).)

* Gemmini case study:
Fortunately, the Gemmini has a dedicated module called "[LoopUnroller](https://github.com/ucb-bar/gemmini/blob/dev/src/main/scala/gemmini/LoopUnroller.scala)". This module dynamically chunk the matrix into smaller matrices, and feed multiple tiled operations to the Load, Execute, and Store unit. Thanks to this unroller module, the Gemmini can expose more general ISA to the software developers. [This testcase](https://github.com/ucb-bar/gemmini-rocc-tests/blob/dev/bareMetalC/tiled_matmul_ws.c) calculates matrix multiplication where the matrix size (64*64 x 64*64) is larger than tile size (16*16) without manually tiling the matrices.

**Comment by minseongg** [comment]
We have updated the google slide to include large matrix multiplication example with `WS` dataflow: [Google Slides (Case 5)](https://docs.google.com/presentation/d/1ff3mA6_p1RbSdiqRT4AH8pPiqOO6C6vVNCpPvkjrU9I/edit?usp=sharing)

We will update to include more examples (e.g. tiled matmul operation with `OS` dataflow, ...)

**Comment by JongyCysec** [comment]
@minseongg @woojinnn 

According to the provided google slide, 
we have several option for tiling and choosing dataflow between ```WS``` and ```OS```.
As @woojinnn described at above, the choices during matrix multiplication can be determined by hardware, compiler, or programmer. 

Recalling the architecture class held by Professor Heo Jae Hyeok, there was a simple cuda programming for matrix multiplication with tiling the computation to several threads. 

However, as I'm not used to architecture of NPU and the way of using it, I'm not sure who is responsible for choosing tiling and dataflow. 

In my simple expectation, using tiling for matrix multiplication is not a big burden for programmer. However, choosing dataflow  will be a more complicated jobs. So I expect hardware or compiler would have to take the responsibility of considering dataflow for matrix multiplication input.

Can I get some opinion or help regarding this issues?

**Comment by woojinnn** [comment]
@JongyCysec I'm not sure if I fully understand the question, but I'll try to answer it first. Let me know if you have the following questions.
> So I expect that NPU hardware takes the responsibility of choosing dataflow type for matrix multiplication because it would be a quite big burden to programmer while choice of tiling can be offloaded to compiler or programmer.

If the hardware meets the expectations set by the ISA, its role is essentially complete.

[The ISA section in the Gemmini documentation](https://github.com/ucb-bar/gemmini/tree/dev?tab=readme-ov-file#config_ex-configures-the-execute-pipeline) (specifically the `config_ex` instruction) provides helpful context here. Gemmini's hardware supports both WS and OS modes and exposes this functionality via the ISA. Once this is in place, the hardware’s responsibility is fulfilled. The remaining tasks—such as selecting the dataflow and tiling strategies—are up to the programmer or the compiler.

You might be concerned about the challenge of having the programmer handle all these decisions (such as in the [Gemmini baremetal testcases](https://github.com/ucb-bar/gemmini-rocc-tests/tree/dev/bareMetalC), where the programmer directly interacts with the hardware). To address this, the compiler (or SDK) is intended to ease the burden. It offers a more abstracted programming model that allows the programmer to focus on higher-level concepts, rather than worrying about the low-level details of hardware configuration.

The same story applies to GPU. In CUDA, the developer doesn’t need to manually manage the GPU’s architecture or handle the details of memory management and parallel execution. Instead, the CUDA compiler (and runtime) takes care of optimizing these low-level operations based on the programmer’s high-level code. The programmer writes their code using CUDA primitives and focuses on parallelism and algorithms, while the compiler ensures the efficient mapping to the GPU hardware.

**Comment by JongyCysec** [comment]
@woojinnn 
I didn't know much about NPU structure,
but thanks to @woojinnn's detailed and friendly explanation, I was able to understand the overall flow. Thank you very much.

**Comment by minseongg** [comment]
In addition to @woojinnn's answer, the Gemmini ISA also defines some CISC-type instructions to help tiling for larger matrix multiplication in the hardware (see [Loop Instructions](https://github.com/ucb-bar/gemmini/tree/dev?tab=readme-ov-file#loop-instructions) section). These instructions do not provide new functionality than writing tiling logic manually, but they are expected to achieve higher throughput compared to write tiling logic manually by non-expert programmers.
