### ISSUE TITLE
HazardFlow Design , Reconfigurable Systolic Array, and Matrix Multiplication. 

### ISSUE THREAD

**Issue by JongyCysec** [kaist-cp/cs492-uarch#63]
# Background

In the design of CPU, several types of hazards (data, control, structural) are inevitable since cpu processes complicated jobs.
So, for programmers who try to design cpu core with HDL, how to deal with hazard is crucial.

At this point, ```Hazardflow``` provides a intuitive interface ```Valid-Ready```, module ```fsm``` and useful combinators based on it, 
focusing on "Dealing with Hazard". 

# HazardFlow & Accelerator Design.

In the design of AI accelerator, it is desirable to avoid hazards as much as possible. 
Hence, unlike CPU design, "Avoiding Hazard" seems more important than "Dealing with Hazard". 
( We may be able to avoid hazard with deploying more registers or modules.)

Then, I wonder what is relative advantage of ```Hazardflow``` programming languages when it comes to accelerator design. 

# Processing Element (PE) design
According to the documentation, tile consists of 2-dimensional processing elements. 
From inputs to outputs during processing, there are only forward signals between processing elements.
So, there is no room for backward signals between ```processing elements```. I expect that it is for maximizing simplicity and efficiency.

# Reconfigurable Systolic Array
If we come up with reconfigurable systolic arrays that allow bidirectional communication between PEs, then we might be able to
leverage relative advantages of ```hazardflow``` design again in NPU design as below.
![image](https://github.com/user-attachments/assets/46d860df-e5b6-4343-abf5-3378b2af739d)

However, the usage of backward signal between ```pe``` would not be related to hazard or stall.
It might be related to reusing partial sums of subsequent ```pe```, sending it to previous ```pe``` , and continuing computation.

# Tiling Matrix Multiplication
When tiling the matrix multiplication, (according to provided google slide materials for tiling) we did not fully compute C(i, j) element. Instead, we compute part of C(i, j) elements in order to reusing weight values as below.
![image](https://github.com/user-attachments/assets/3fda57c2-20ac-4c19-8e2a-35d777425a19)

If we allow backward signal between ```pe```s in reconfigurable systolic array, then I expect that we may be able to calculate output element C(i, j) at once. 

Since I'm not used to NPU & systolic array design, so it would be thankful if I can get some opinions or feedback about such issues.

**Comment by minseongg** [comment]
Your proposed method sounds interesting. I'll explain how Gemmini NPU handles the matmul operations, and then I'll describe how your approach could be applied to them.

Let me give you an overview of how the Controller in the Gemmini NPU which handles matmul operation (`C = A * B + D`, each matrix fits the size of the systolic array). Here is the overall structure:

<p align="center">
  <img src="https://github.com/user-attachments/assets/b3eeebdd-421e-4b38-ae5f-de6f84965f7b" width=80% />
</p>

1. A command representing the matmul operation arrives at the controller's ingress interface. This command includes the SRAM address for input matrices A, B, and D, the SRAM address to store output matrix C, and other metadata information.
2. The controller sends a read request to SRAM to fetch the data for input matrices A, B, and D. At this point, the current matmul operation in the systolic array might create a RAW dependency between its SRAM write address and the SRAM address needed by the incoming operation. As a result, the incoming matmul operation waits until the RAW hazard is resolved. The SRAM write address information for the current matmul operation is received from the FIFO as a resolver.
3. Once the read response is received from SRAM, the data for matrices A, B, and D is loaded into the systolic array and the FIFO.
4. When the matmul result is ready, a write request is send to the SRAM to store output matrix C, and the operation exits through the controller's egress interface.

Here, we can see that the controller communicates with an external SRAM module to manage the input and output values of the systolic array (It is quite common because we don't know when the partial sums from the systolic array might need to be reused).

However, in cases where a RAW hazard occurs, the output from the current systolic array operation is required as input for the next matmul operation. In this case, I think we could bypass the output directly back to the input as a resolver signal, as you proposed. This approach could help hide memory latency from SRAM read/write and may reduce the overall latency. I believe this scenario could be useful when performing matmul on matrices that are a few times larger than the systolic array size (e.g., performing 4x4 matmul using a 2x2 systolic array).

My answer might not be accurate and appliable, but thank you for the insightful question!
