### ISSUE TITLE
[Assignment6] Transposer selection logic

### ISSUE THREAD

**Issue by JongyCysec** [kaist-cp/cs492-uarch#77]
According to the documentation of assignment 6, it is said that **For some combinations which require more than one matrix to be transposed, it is guaranteed that they are not given as input.**

And attached table in the documentation is as below. 
![image](https://github.com/user-attachments/assets/02be6a3d-1141-4a45-a2e2-d8e9e91f6626)

In case of, ```OS``` dataflow, 
I expect that transposer selector result should be ```invalid``` for (trans_a = true, trans_bd = true).
And selector result of (trans_a = false, trans_bd = true) should be (a_sel = 0, b_sel = 1, d_sel = 0).

However, the unit test succeeds with the original table in the documentation but fails with my modified table explained above.

So, there might be something that I mis-understood. 

Can I request for some help with this issue?

**Comment by woojinnn** [comment]
In the next class will be about Execute module so that you can understand Assignment 6 more precisely. To give you a quick answer to your question,
* Invalid cases are from [Gemmini readme](https://github.com/ucb-bar/gemmini/tree/dev?tab=readme-ov-file#config_ex-configures-the-execute-pipeline).
  * ![image](https://github.com/user-attachments/assets/2920eda3-27f1-4e24-8443-effe3c2a3291)
* By default, in OS mode, Matrix A must enter transposer to calculate the matrix product in non-transposed form. We will explain about it in the next class in detail.

**Comment by JongyCysec** [comment]
Thank you for your answer!!

**Comment by woojinnn** [comment]
@JongyCysec 
Very simple, teaser illustration about transposing A matrix under OS mode:
![image](https://github.com/user-attachments/assets/5c49555c-7e08-418c-9a6e-d512c5406bca)
