### ISSUE TITLE
[Assignment 5] Hazardflow panics if I try to use pe from assignment 4

### ISSUE THREAD

**Issue by JustinKim98** [kaist-cp/cs492-uarch#79]
in implementation of `tile_with_reg` function in assignment 5, 
the default implementation given uses `tile` function defined in `tile.rs` which uses `pe` implemented outside.

**However, if I try to change `pe_ffi` to `pe` which I implemented on assignment 4, hazardflow panics during the build process.**
(I passed all tests given in assignment 4)

Is this an expected behavior? If it is, should we use `pe_ffi` instead `pe` for assignment 5?
(My implementation in assignment 5 passes tests if I use `pe_ffi`)

**Comment by minseongg** [comment]
Oh, yes! It was intended to use `pe_ffi`, we use the original Gemmini PE implementation in the Assignment 5.

FYI: The reason of the panic is due to the `#[synthesize]` attribute in the PE function, the hazardflow compiler currently panic if that attribute is in a function which is not a top module.

**Comment by JustinKim98** [comment]
Thank you for your answer!
