### ISSUE TITLE
"Failed to run proc-macro server" on vscode

### ISSUE THREAD

**Issue by Kwanghoon-Choi** [kaist-cp/cs492-uarch#97]
Hi, have anyone encountered the warning message with "synthesize: Failed to run proc-macro server from path..."?

I googled it and it was related to rustc or rustup, but they are not installed on the development server. (I have also updated my vscode to the latest version)
I don't think the warning would make the compilation fail, but just in case something that I am not aware of happens.

(I guess the waning pops up since I did "cargo build -p hazardflow-macro", but I am not sure.)

<img width="681" alt="20241218_150159" src="https://github.com/user-attachments/assets/30f7edc4-3029-40b3-8148-a7a8924be1b0" />

**Comment by minseongg** [comment]
I also sometimes encounter that warnings when using the rust-analyzer extension on VSCode + macOS.

I suspect the issue might be related to the proc-macro features in that extension, but I’m not entirely sure.

Since these warnings don’t cause compilation to fail, I recommend ignoring them for now. If I find a solution, I’ll share it with you. Sorry for the inconvenience!

**Comment by Kwanghoon-Choi** [comment]
It is totally fine if the compilation has no problem. I'll share my solution if I find one too. Thank you for quick response!
